CREATE TABLE IF NOT EXISTS ATTENDANCE_INFO (
    USER_ID VARCHAR(5),
    SCHEDULED_ATTENDANCE_DATE VARCHAR(20),
    SCHEDULED_ATTENDANCE_TIME VARCHAR(20),
    SCHEDULED_LEAVING_TIME VARCHAR(20),
    ACHIEVED_ATTENDANCE_TIME TEXT,
    ACHIEVED_LEAVING_TIME TEXT,
    ATTEND_FLG BOOLEAN,
    LEAVE_FLG BOOLEAN,
    CREATE_USER TEXT,
    UPDATE_USER TEXT,
    CREATE_DATE_TIME TEXT,
    UPDATE_DATE_TIME TEXT,
    PRIMARY KEY(USER_ID,SCHEDULED_ATTENDANCE_DATE)
 );