CREATE TABLE IF NOT EXISTS ATTENDANCE_INFO (
    USER_ID VARCHAR(5),
    SCHEDULED_ATTENDANCE_DATE VARCHAR(20),
    SCHEDULED_LEAVING_DATE VARCHAR(20),
    SCHEDULED_ATTENDANCE_TIME VARCHAR(20),
    SCHEDULED_LEAVING_TIME VARCHAR(20),
    ACHIEVED_ATTENDANCE_DATE TEXT,
    ACHIEVED_LEAVING_DATE TEXT,
    ACHIEVED_ATTENDANCE_TIME TEXT,
    ACHIEVED_LEAVING_TIME TEXT,
    CREATE_USER TEXT,
    UPDATE_USER TEXT,
    CREATE_DATE_TIME TEXT,
    UPDATE_DATE_TIME TEXT,
    PRIMARY KEY(SCHEDULED_ATTENDANCE_DATE,SCHEDULED_LEAVING_DATE,SCHEDULED_ATTENDANCE_TIME,SCHEDULED_LEAVING_TIME)
);