CREATE TABLE IF NOT EXISTS ATTENDANCE_INFO (
    ATTENDANCE_ID INT(5) PRIMARY KEY AUTO_INCREMENT,
    USER_ID VARCHAR(5),
    SCHEDULED_ATTENDANCE_DATE TEXT,
    SCHEDULED_LEAVING_DATE TEXT,
    ACHIEVED_ATTENDANCE_DATE TEXT,
    ACHIEVED_LEAVING_DATE TEXT,
    SCHEDULED_ATTENDANCE_TIME TEXT,
    SCHEDULED_LEAVING_TIME TEXT,
    ACHIEVED_ATTENDANCE_TIME TEXT,
    ACHIEVED_LEAVING_TIME TEXT,
    CREATE_USER TEXT,
    UPDATE_USER TEXT,
    CREATE_DATE_TIME TEXT,
    UPDATE_DATE_TIME TEXT
);