
CREATE TABLE IF NOT EXISTS USER_INFO (
    USER_ID VARCHAR(5) PRIMARY KEY,
    EMAIL_ADDRESS TEXT,
    PASSWORD TEXT,
    CREATE_USER TEXT,
    UPDATE_USER TEXT,
    CREATE_DATE_TIME TEXT,
    UPDATE_DATE_TIME TEXT
);